### ISSUE TITLE
commands tracking issue

### ISSUE THREAD

**Issue by felixangell** [felixangell/phi#46]
these are the commands that need to be implemented (with links to their relevant issues):

* [x] open file  `ctrl+o` (depends on command palette)
* [x] close file `ctrl+w`
* [x] exit editor `ctrl+q`
* [ ] copy to clipboard  `ctrl+c` (depends on shift selection)
* [x] paste to current buffer `ctrl+v`
* [ ] cut  `ctrl+x` (depends on shift selection)
* [x] goto line  `ctrl+l` (depends on command palette)
* [x] undo `ctrl+z`
* [x] redo
* [x] new buffer `ctrl+t`
* [ ] 

Any missing ones please comment!
